version: "3.8"

services:
  express-js-es6-api-minuman-kekinian-docker:
    container_name: 'express-js-es6-api-minuman-kekinian-docker'
    build:
      context: "."
      dockerfile: Dockerfile
    image: "express-js-es6-api-minuman-kekinian-docker:1.0.0"
    environment:
      - "NODE_ENV=development"
    ports:
      - protocol: tcp
        published: 3500
        target: 3500
    volumes:
      - .:/app/
      - /app/node_modules
    command: npm run dev
